@startuml
'https://plantuml.com/class-diagram
skinparam style strictuml
skinparam classAttributeIconSize 0
skinparam classFontStyle Bold
hide empty members

Class TD6.Scenario3.Boisson{

+ Boisson(java.lang.String,TD6.Scenario3.Genre)(java.lang.String nom, TD6.Scenario3.Genre genre)

+ getNom() : ()java.lang.String
+ getGenre() : ()TD6.Scenario3.Genre

}
TD6.Scenario3.Boisson -- TD6.Scenario3.Genre


Class TD6.Scenario3.Brigand{
- recompense

+ Brigand(java.lang.String)(java.lang.String nom)
+ Brigand(java.lang.String,TD6.Scenario3.Boisson)(java.lang.String nom, TD6.Scenario3.Boisson boisson)
+ Brigand(java.lang.String,TD6.Scenario3.Boisson,java.lang.String)(java.lang.String nom, TD6.Scenario3.Boisson boisson, java.lang.String look)

+ getLook() : ()java.lang.String
+ setLook() : 
+ getPseudonyme() : ()java.lang.String
+ getStrRecompense() : ()java.lang.String
+ getRecompense() : ()int
+ getDames() : ()java.util.List<TD6.Scenario3.Dame>
+ kidnapper() : 
+ seFaireCapturer() : 
+ isLibre() : ()java.lang.Boolean
+ getCaptureur() : ()TD6.Scenario3.Cowboy
+ sePresenter() : 

}
TD6.Scenario3.Brigand -- TD6.Scenario3.Cowboy
TD6.Scenario3.Brigand -- java.lang.Boolean
TD6.Scenario3.Brigand - TD6.Scenario3.Dame

TD6.Scenario3.Brigand ---|> TD6.Scenario3.Personnage
Class TD6.Scenario3.Cowboy{
- somme

+ Cowboy(java.lang.String)(java.lang.String nom)
+ Cowboy(java.lang.String,TD6.Scenario3.Boisson)(java.lang.String nom, TD6.Scenario3.Boisson boisson)

+ getPseudonyme() : ()java.lang.String
+ getDamLibre() : ()java.util.List<TD6.Scenario3.Dame>
+ tirerSur() : 
+ capturer() : 
+ getSomme() : ()int
+ sePresenter() : 

}
TD6.Scenario3.Cowboy - TD6.Scenario3.HorsLaLoi
TD6.Scenario3.Cowboy - TD6.Scenario3.Dame

TD6.Scenario3.Cowboy ---|> TD6.Scenario3.Personnage
Class TD6.Scenario3.Dame{

+ Dame(java.lang.String)(java.lang.String nom)

+ getPseudonyme() : ()java.lang.String
+ isLibre() : ()java.lang.Boolean
+ seFaireEnlever() : 
+ seFaireLiberer() : 
+ getSauveur() : ()TD6.Scenario3.Cowboy
+ getEscroc() : ()TD6.Scenario3.HorsLaLoi
+ sePresenter() : 

}
TD6.Scenario3.Dame -- java.lang.Boolean
TD6.Scenario3.Dame -- TD6.Scenario3.Cowboy
TD6.Scenario3.Dame -- TD6.Scenario3.HorsLaLoi

TD6.Scenario3.Dame ---|> TD6.Scenario3.Personnage
Enum TD6.Scenario3.Genre<<enum>> {
MASCULIN
FEMININ

}
Class TD6.Scenario3.Histoire3{

+ Histoire3()()

{static} + main() : 

}


Class TD6.Scenario3.Histoire4{

+ Histoire4()()

{static} + main() : 

}


Interface TD6.Scenario3.HorsLaLoi<<interface>> {
}
Class TD6.Scenario3.Narrateur{

+ Narrateur(java.lang.String)(java.lang.String nom)

+ getPseudonyme() : ()java.lang.String
+ boire() : 

}

TD6.Scenario3.Narrateur ---|> TD6.Scenario3.Personnage
Class TD6.Scenario3.Personnage{

+ Personnage(java.lang.String,TD6.Scenario3.Boisson)(java.lang.String nom, TD6.Scenario3.Boisson boisson)
+ Personnage(java.lang.String)(java.lang.String nom)

+ getNom() : ()java.lang.String
+ getPrefere() : ()TD6.Scenario3.Boisson
+ setPrefere() : 
+ sePresenter() : 
+ boire() : 
+ dire() : 
+ boire() : 
abstract + getPseudonyme() : ()java.lang.String

}
TD6.Scenario3.Personnage -- TD6.Scenario3.Boisson


Class TD6.Scenario3.Ripou{
- recompense
- somme

+ Ripou(java.lang.String)(java.lang.String nom)
+ Ripou(java.lang.String,TD6.Scenario3.Boisson)(java.lang.String nom, TD6.Scenario3.Boisson boisson)
+ Ripou(java.lang.String,TD6.Scenario3.Boisson,java.lang.String)(java.lang.String nom, TD6.Scenario3.Boisson boisson, java.lang.String look)

+ getPseudonyme() : ()java.lang.String
+ isLibre() : ()java.lang.Boolean
+ getLook() : ()java.lang.String
+ getRecompense() : ()int
+ getStrRecompense() : ()java.lang.String
+ getDames() : ()java.util.List<TD6.Scenario3.Dame>
+ kidnapper() : 
+ seFaireCapturer() : 
+ getCaptureur() : ()TD6.Scenario3.Cowboy
+ sePresenter() : 
+ capturer() : 

}
TD6.Scenario3.Ripou - TD6.Scenario3.Brigand
TD6.Scenario3.Ripou - TD6.Scenario3.Dame
TD6.Scenario3.Ripou -- TD6.Scenario3.Cowboy
TD6.Scenario3.Ripou -- java.lang.Boolean

TD6.Scenario3.Ripou ---|> TD6.Scenario3.Cowboy
@enduml

