@startuml
'https://plantuml.com/class-diagram
skinparam style strictuml
skinparam classAttributeIconSize 0
skinparam classFontStyle Bold
hide empty members

Class TD6.Scenario3.Boisson{
+ <<create>> Boisson(nom: String, genre: Genre)
- nom: String
- genre: Genre
+ getNom(): String
+ getGenre(): Genre

}
TD6.Scenario3.Boisson -- TD6.Scenario3.Genre


Class TD6.Scenario3.Brigand{
+ <<create>> Brigand(nom: String)
+ <<create>> Brigand(nom: String, boisson: Boisson)
+ <<create>> Brigand(nom: String, boisson: Boisson, look: String)
- recompense: int
- look: String
- captureur: Cowboy
- libre: Boolean
- Dames: Dame[*]
+ getLook(): String
+ setLook(look: String)
+ getPseudonyme(): String
+ getStrRecompense(): String
+ getRecompense(): int
+ getDames(): Dame[*]
+ kidnapper(dame: Dame)
+ seFaireCapturer(cowboy: Cowboy)
+ isLibre(): Boolean
+ getCaptureur(): Cowboy
+ sePresenter()

}
TD6.Scenario3.Brigand -- TD6.Scenario3.Cowboy

TD6.Scenario3.Brigand ---|> TD6.Scenario3.Personnage
Class TD6.Scenario3.Cowboy{
+ <<create>> Cowboy(nom: String)
+ <<create>> Cowboy(nom: String, boisson: Boisson)
- somme: int
- lstBrigand: HorsLaLoi[*]
- damLibre: Dame[*]
+ getPseudonyme(): String
+ getDamLibre(): Dame[*]
+ tirerSur(brigand: HorsLaLoi)
+ capturer(horsLaLoi: HorsLaLoi)
+ getSomme(): int
+ sePresenter()

}

TD6.Scenario3.Cowboy ---|> TD6.Scenario3.Personnage
Class TD6.Scenario3.Dame{
+ <<create>> Dame(nom: String)
- Libre: Boolean
- sauveur: Cowboy
- escroc: HorsLaLoi
+ getPseudonyme(): String
+ isLibre(): Boolean
+ seFaireEnlever(horsLaLoi: HorsLaLoi)
+ seFaireLiberer(cowboy: Cowboy)
+ getSauveur(): Cowboy
+ getEscroc(): HorsLaLoi
+ sePresenter()

}
TD6.Scenario3.Dame -- TD6.Scenario3.Cowboy
TD6.Scenario3.Dame -- TD6.Scenario3.HorsLaLoi

TD6.Scenario3.Dame ---|> TD6.Scenario3.Personnage
Enum TD6.Scenario3.Genre<<enum>> {
MASCULIN
FEMININ

}
Class TD6.Scenario3.Histoire3{
+ <<create>> Histoire3()
{static} + main(args: String[])

}


Class TD6.Scenario3.Histoire4{
+ <<create>> Histoire4()
{static} + main(args: String[])

}


Interface TD6.Scenario3.HorsLaLoi<<interface>> {
{abstract} + getPseudonyme(): String
{abstract} + getLook(): String
{abstract} + getDames(): Dame[*]
{abstract} + kidnapper(dame: Dame)
{abstract} + seFaireCapturer(cowboy: Cowboy)
{abstract} + getRecompense(): int
{abstract} + isLibre(): Boolean
{abstract} + getCaptureur(): Cowboy
{abstract} + sePresenter()
{abstract} + dire(phrase: String)

}

Interface TD6.Scenario3.ITest<<interface>> {

}
TD6.Scenario3.ITest ---|> TD6.Scenario3.HorsLaLoi

Class TD6.Scenario3.Narrateur{
+ <<create>> Narrateur(nom: String)
+ getPseudonyme(): String
+ boire(boisson: Boisson)

}

TD6.Scenario3.Narrateur ---|> TD6.Scenario3.Personnage
Class TD6.Scenario3.Personnage{
+ <<create>> Personnage(nom: String, boisson: Boisson)
+ <<create>> Personnage(nom: String)
- nom: String
- prefere: Boisson
+ getNom(): String
+ getPrefere(): Boisson
+ setPrefere(prefere: Boisson)
+ sePresenter()
+ boire(boisson: Boisson)
+ dire(phrase: String)
+ boire()
{abstract} + getPseudonyme(): String

}
TD6.Scenario3.Personnage -- TD6.Scenario3.Boisson


Class TD6.Scenario3.Ripou{
+ <<create>> Ripou(nom: String)
+ <<create>> Ripou(nom: String, boisson: Boisson)
+ <<create>> Ripou(nom: String, boisson: Boisson, look: String)
- recompense: int
- somme: int
- lstBrigand: Brigand[*]
- Dames: Dame[*]
- look: String
- captureur: Cowboy
- libre: Boolean
+ getPseudonyme(): String
+ isLibre(): Boolean
+ getLook(): String
+ getRecompense(): int
+ getStrRecompense(): String
+ getDames(): Dame[*]
+ kidnapper(dame: Dame)
+ seFaireCapturer(cowboy: Cowboy)
+ getCaptureur(): Cowboy
+ sePresenter()
+ capturer(horsLaLoi: HorsLaLoi)

}
TD6.Scenario3.Ripou -- TD6.Scenario3.Cowboy

TD6.Scenario3.Ripou ---|> TD6.Scenario3.Cowboy

@enduml

