@startuml
'https://plantuml.com/sequence-diagram
skinparam style strictuml
skinparam classAttributeIconSize 0
skinparam classFontStyle Bold
hide empty members



class FirstDoclet implements Doclet
{
}

interface Doclet
{
}



class Option

enum SourceVersion
{
}

interface DocletEnvironment
{
}

interface Element
{

}

FirstDoclet ..> Element : <<use>>
FirstDoclet ..> DocletEnvironment : <<use>>
FirstDoclet ..> SourceVersion : <<use>>
FirstDoclet ..> Option : <<use>>



@enduml