@startuml
'https://plantuml.com/class-diagram
skinparam style strictuml
skinparam classAttributeIconSize 0
skinparam classFontStyle Bold
hide empty members

Class Boisson{

}
Class Brigand{
recompense

}
Class Cowboy{
somme

}
Class Dame{

}
Enum Genre<<enum>> {
MASCULIN
FEMININ

}
Class Histoire3{

}
Class Histoire4{

}
Interface HorsLaLoi<<interface>> {
}
Class Narrateur{

}
Class Personnage{

}
Class Ripou{
recompense
somme

}
@enduml

