@startuml
'https://plantuml.com/class-diagram
skinparam style strictuml
skinparam classAttributeIconSize 0
skinparam classFontStyle Bold
hide empty members

Class western.Boisson{

}
western.Boisson - western.Substantif
western.Boisson - western.Boisson

Class western.Brigand{
recompense
estLibre

}
western.Brigand - western.Dame
western.Brigand - western.Cowboy
western.Brigand - western.Boisson

Class western.CasDeTestStandard{

}

Class western.Cowboy{
gains

}
western.Cowboy - western.HorsLaLoi
western.Cowboy - western.Boisson

Class western.Dame{
estLibre

}
western.Dame - western.Cowboy
western.Dame - western.HorsLaLoi
western.Dame - western.Boisson

Enum western.Genre<<enum>> {
FEMININ
MASCULIN

}
Class western.Histoire4{

}

Interface western.HorsLaLoi<<interface>> {
}
Class western.Narrateur{

}

Interface western.Nommable<<interface>> {
}
Class western.Personnage{

}
western.Personnage - western.Boisson
western.Personnage - western.Boisson

Class western.Ripou{

}
western.Ripou - western.Brigand

Class western.Substantif{

}
western.Substantif - western.Genre

Class western.test{

}

@enduml

